### ISSUE TITLE
Enable lists.w3.org mailing list for socialcg

### ISSUE THREAD

**Issue by gobengo** [swicg/general#25]
Is there a SocialCG lists.w3.org mailing list?
There is a link of "Contact this Group" at https://www.w3.org/community/SocialCG/

But I can't discover it from here: https://lists.w3.org
Or access archives at: https://lists.w3.org/Archives/Public/public-socialcg/

Can we have a mailing list please?

There are at least two relevant considerations here:
1. Does anyone have strong opinions against there being one?
2. Who could enable it?
    * /cc @rhiaro @cwebber @msporny please at-mention anyone you know who might have permissions to enable this if consideration #1 is not a blocker.

Update: I sent an email to the address linked to from the SocialCG homepage and got a bounce:
> Your message wasn't delivered to public-socialcg@w3.org because the address couldn't be found, or is unable to receive mail.

**Comment by rhiaro** [comment]
I'm +1 enabling the mailing list given that there is no obvious place for asynchronous comms that will reach all of those interested for swicg at the moment. (IRC is all well and good for those who can navigate access *and* remain connected all the time *and* have the capacity to read logs and mentally filter things that aren't interesting, but it's impossible to have a long running threaded conversation that way, or keep up with the overall topics on peoples' radars.)

It's important we point at a CoC for the list (W3C's existing one, probably) and have a few people on hand to moderate if necessary ahead of time, rather than waiting for something bad to happen and reacting.

Push back against mailing lists in the past has been, I believe, due to the tendency towards people sending giant essay-like messages, and putting a lot of time into that over actually building things. Perhaps we could add something to the list guidelines to discourage this - encourage people to write out their ideas as a blog post and send a link to the list maybe. (But also if someone wants to spend all the time writing emails and not doing anything else that's their prerogative, and fortunately nobody is required to read or reply, and mail filters work well enough to hide particular threads from people who'd rather not know they're ongoing if need be.)

Maybe @sandhawke can turn it on? Otherwise I can ping w3c sysreq, but it won't be this week due to TPAC.

**Comment by nightpool** [comment]
I have strong opinions against adding yet another platform to monitor communications on with no clear usecase—this has been discussed before, and the consensus of the group was to use Github issues and IRC as our primary collaboration platforms. Github issues is already a place for asynchronous comms, and we just resolved to add another one in the last meeting in the form of a Discourse forum maintained by the community. Adding a third place for asynchronous comms seems really bad.

**Comment by jaywink** [comment]
Depends what is the focus of the Social Web Incubator Community Group. Is it purely ActivityPub? I believe not? I believe the forum is only ActivityPub, or so I understood at least.

Not that adding more mediums wouldn't be confusing :)

**Comment by nightpool** [comment]
>I believe the forum is only ActivityPub, or so I understood at least.

That's a good point, although I'm not sure if the forum is activitypub-only or if that was just the most convenient domain name we had lying around. That said, I think my point still stands—we already have this github repo for async discussions.

**Comment by akuckartz** [comment]
The mailing list was enabled in November 2022. See https://lists.w3.org/Archives/Public/public-swicg/2022Nov/0001.html

Can someone please close this issue?
